server:
  port: 8080 # Gateway uygulaması farklı bir portta çalışacak

spring:
  application:
    name: airline-api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        # User Service
        - id: user_service
          uri: http://localhost:8087
          predicates:
            - Path=/api/users/**
        # Ticket Service
        - id: ticket_service
          uri: http://localhost:8087
          predicates:
            - Path=/api/tickets/**
        # Listing Service
        - id: listing_service
          uri: http://localhost:8087
          predicates:
            - Path=/api/listings/**
        # Flight Service
        - id: flight_service
          uri: http://localhost:8087
          predicates:
            - Path=/api/flights/**
        # Booking Service
        - id: booking_service
          uri: http://localhost:8087
          predicates:
            - Path=/api/bookings/**
        # Authentication Service
        - id: auth_service
          uri: http://localhost:8087
          predicates:
            - Path=/api/auth/**
        - id: message_service
          uri: http://localhost:8088
          predicates:
            - Path=/api/messages/**
        - id: payment_service
          uri: http://localhost:8090
          predicates:
            - Path=/api/payments/**
        - id: notification_service
          uri: http://localhost:8091
          predicates:
            - Path=/api/notifications/**

      default-filters:
        - AddRequestHeader=X-Request-Id, some-value

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG



